### ISSUE TITLE
升级到Typecho 1.2 后插件出错

### ISSUE THREAD

**Issue by xzyone** [typecho/typecho#1140]
### 1. 该问题的重现步骤是什么？
使用 master 分支最新代码 09a320b，从开发版1.1升级。
使用upyun插件上传文件出现错误。
### 2. 你期待的结果是什么？实际看到的又是什么？

```
VM587:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.w.parseJSON (jquery.js?v=1.2.0:1)
    at U.Uploader.FileUploaded (write-post.php:1092)
    at U.Uploader.dispatchEvent (plupload.js?v=1.2.0:1)
    at U.Uploader.trigger (moxie.js?v=1.2.0:1)
    at k.m.onload (plupload.js?v=1.2.0:1)
    at k.<anonymous> (moxie.js?v=1.2.0:1)
    at Array.<anonymous> (moxie.js?v=1.2.0:1)
    at r (moxie.js?v=1.2.0:1)
    at Object.f [as inSeries] (moxie.js?v=1.2.0:1)
```

### 3. 问题出现的环境

- 操作系统版本：CentOS 8.0
- Apache/NGINX 版本：Nginx 1.19.6
- 数据库版本：MySQL 5.7.32
- PHP 版本：PHP 7.4
- Typecho 版本 Typecho 1.2
- 浏览器版本：Chrome

[//]: # (如有图片请附上截图)
![image](https://user-images.githubusercontent.com/23356216/130380807-4186cdac-449f-4348-8b8b-ca6d689c5aac.png)

**Comment by joyqi** [comment]
请把这个ajax请求的response文本贴出来

**Comment by xzyone** [comment]
/action/upload?_=7785357d23e5feec3b1da19d036486f1

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Error</title>
        <style>
            html {
                padding: 50px 10px;
                font-size: 16px;
                line-height: 1.4;
                color: #666;
                background: #F6F6F3;
                -webkit-text-size-adjust: 100%;
                -ms-text-size-adjust: 100%;
            }

            html,
            input { font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; }
            body {
                max-width: 500px;
                _width: 500px;
                padding: 30px 20px;
                margin: 0 auto;
                background: #FFF;
            }
            ul {
                padding: 0 0 0 40px;
            }
            .container {
                max-width: 380px;
                _width: 380px;
                margin: 0 auto;
            }
        </style>
    </head>
    <body>
        <div class="container">
            Call to undefined method Typecho_Common::isAppEngine()
        </div>
    </body>
</html>
```

请问是这个吗？

**Comment by joyqi** [comment]
在config里定义
```
define('__TYPECHO_DEBUG__', true);
```

再看看response

**Comment by xzyone** [comment]
```
<pre><code><h1>Call to undefined method Typecho_Common::isAppEngine()</h1>Error: Call to undefined method Typecho_Common::isAppEngine() in /www/wwwroot/hong/usr/plugins/UpyunFile/Plugin.php:134
Stack trace:
#0 /www/wwwroot/hong/var/Typecho/Plugin.php(516): UpyunFile_Plugin::uploadHandle()
#1 /www/wwwroot/hong/var/Widget/Upload.php(368): Typecho_Plugin-&gt;__call()
#2 /www/wwwroot/hong/var/Widget/Upload.php(305): Widget_Upload::uploadHandle()
#3 /www/wwwroot/hong/var/Widget/Upload.php(92): Widget_Upload-&gt;upload()
#4 /www/wwwroot/hong/var/Widget/Do.php(82): Widget_Upload-&gt;action()
#5 /www/wwwroot/hong/var/Typecho/Widget.php(168): Widget_Do-&gt;execute()
#6 /www/wwwroot/hong/var/Typecho/Router.php(110): Typecho_Widget::widget()
#7 /www/wwwroot/hong/index.php(28): Typecho_Router::dispatch()
#8 {main}</code></pre>
```

**Comment by xzyone** [comment]
哦了，删了AppEngine()所在的语句就好了，谢谢大佬。是1.2版本把这个函数去掉了吗？

**Comment by joyqi** [comment]
是的，这个函数判断没啥用了，我后面给它加上吧，做个假的入口

**Comment by xzyone** [comment]
> 是的，这个函数判断没啥用了，我后面给它加上吧，做个假的入口

这个函数确实没啥用，主题和插件作者到时候把它删掉就行。
我又遇见了一个问题，主题提示Call to a member function getRequestUrl() on null

<pre><code><h1>Call to a member function getRequestUrl() on null</h1>Error: Call to a member function getRequestUrl() on null in /www/wwwroot/blog/usr/themes/Mirages/lib/Content.php:596
Stack trace:
#0 /www/wwwroot/blog/usr/themes/Mirages/component/header.php(100): Content::outputCommentJS()
#1 /www/wwwroot/blog/var/Widget/Archive.php(1305): require('/www/wwwroot/bl...')
#2 /www/wwwroot/blog/usr/themes/Mirages/post.php(2): Widget_Archive-&gt;need()
#3 /www/wwwroot/blog/var/Widget/Archive.php(1390): require_once('/www/wwwroot/bl...')
#4 /www/wwwroot/blog/var/Typecho/Router.php(113): Widget_Archive-&gt;render()
#5 /www/wwwroot/blog/index.php(23): Typecho_Router::dispatch()
#6 {main}</code></pre>

**Comment by joyqi** [comment]
https://github.com/typecho/typecho/pull/1137

**Comment by xzyone** [comment]
好的谢谢大佬
