### ISSUE TITLE
master分支最新版，全新安装时报错

### ISSUE THREAD

**Issue by noisky** [typecho/typecho#1152]
### 1. 该问题的重现步骤是什么？
直接clone master分支最新版
`git clone https://github.com/typecho/typecho.git`
安装页面报错
```
Missing Database Object
Typecho\Db\Exception: Missing Database Object in F:\Develop\PHPStormProject\typecho-new\var\Typecho\Db.php:277
Stack trace:
#0 F:\Develop\PHPStormProject\typecho-new\var\Widget\Base.php(82): Typecho\Db::get()
#1 F:\Develop\PHPStormProject\typecho-new\var\Typecho\Widget.php(94): Widget\Base->init()
#2 F:\Develop\PHPStormProject\typecho-new\var\Typecho\Widget.php(150): Typecho\Widget->__construct(Object(Typecho\Widget\Request), Object(Typecho\Widget\Response), Array)
#3 F:\Develop\PHPStormProject\typecho-new\var\Typecho\Widget.php(183): Typecho\Widget::widget('Widget\\Options', Array, NULL, true)
#4 F:\Develop\PHPStormProject\typecho-new\install.php(1372): Typecho\Widget::alloc(Array)
#5 F:\Develop\PHPStormProject\typecho-new\install.php(1447): install_dispatch()
#6 {main}
```

### 3. 问题出现的环境

- 操作系统版本：Debian 10 / Win10
- Apache/NGINX 版本：nginx/1.20.1
- 数据库版本：MySQl  v8.0.25
- PHP 版本：7.4.20
- Typecho 版本：master分支最新版
- 浏览器版本：Microsoft Edge 93.0.961.38

[//]: # (如有图片请附上截图)
![QQ20210907152814.png](https://img.ffis.me/images/2021/09/07/QQ20210907152814.png)

**Comment by JohnsonRan** [comment]
刚测试我Typecho-Docker项目时也是这样，我以为我哪里写错了 （
