### ISSUE TITLE
1.2.0-beta.1 报错 Undefined constant

### ISSUE THREAD

**Issue by iKirby** [typecho/typecho#1155]
### 1. 该问题的重现步骤是什么？

把服务器上的文件替换为 1.2.0-beta.1

### 2. 你期待的结果是什么？实际看到的又是什么？

期待结果正常运行。实际出现错误：

```
[08-Sep-2021 14:20:16] WARNING: [pool www] child 75711 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "Typecho\__TYPECHO_CLASS_ALIASES__" in /home/wwwroot/ikirby.me/var/Typecho/Common.php:104"
[08-Sep-2021 14:20:16] WARNING: [pool www] child 75711 said into stderr: "Stack trace:"
[08-Sep-2021 14:20:16] WARNING: [pool www] child 75711 said into stderr: "#0 /home/wwwroot/ikirby.me/config.inc.php(52): Typecho\{closure}()"
[08-Sep-2021 14:20:16] WARNING: [pool www] child 75711 said into stderr: "#1 /home/wwwroot/ikirby.me/index.php(11): include_once('...')"
[08-Sep-2021 14:20:16] WARNING: [pool www] child 75711 said into stderr: "#2 {main}"
[08-Sep-2021 14:20:16] WARNING: [pool www] child 75711 said into stderr: "  thrown in /home/wwwroot/ikirby.me/var/Typecho/Common.php on line 104"
```

### 3. 问题出现的环境

- 操作系统版本：Ubuntu 20.04
- Apache/NGINX 版本：Caddy 2.4.3
- 数据库版本：MariaDB 10.3
- PHP 版本：8.0.9
- Typecho 版本：1.2.0-beta.1
- 浏览器版本：Chrome 93

**Comment by benzBrake** [comment]
config.inc.php 你没修改 config.inc.php 的格式吧

**Comment by iKirby** [comment]
@benzBrake config.inc.php 需要做哪些修改？我没看到相关说明啊...
