### ISSUE TITLE
疑似 Typeche master branch 的 bug

### ISSUE THREAD

**Issue by benzBrake** [typecho/typecho#1168]
### 1. 该问题的重现步骤是什么？
安装，[AutoBackup](https://github.com/benzBrake/AutoBackup) 插件，启用，配置好信息，访问备份调用接口，报错。
### 2. 你期待的结果是什么？实际看到的又是什么？
报错信息如下，疑似为master branch 的 Typecho 的 bug
```
Return value of Typecho\Widget::widget() must be an instance of Typecho\Widget, instance of AutoBackup_Action returned
TypeError: Return value of Typecho\Widget::widget() must be an instance of Typecho\Widget, instance of AutoBackup_Action returned in E:\WorkSpace\development\wwwroot\var\Typecho\Widget.php:174
Stack trace:
#0 E:\WorkSpace\development\wwwroot\var\Widget\Action.php(68): Typecho\Widget::widget('AutoBackup_Acti...')
#1 E:\WorkSpace\development\wwwroot\var\Typecho\Widget.php(155): Widget\Action->execute()
#2 E:\WorkSpace\development\wwwroot\var\Typecho\Router.php(96): Typecho\Widget::widget('Widget_Do', NULL, Array)
#3 E:\WorkSpace\development\wwwroot\index.php(23): Typecho\Router::dispatch()
#4 {main}
```
### 3. 问题出现的环境
- Typecho 版本：master branch 最新

[//]: # (如有图片请附上截图)

**Comment by joyqi** [comment]
这个插件写的不够严格，应该`extends Typecho_Widget`
