### ISSUE TITLE
评论邮箱提醒插件回复时报错

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#1192]
插件地址：https://gitee.com/HoeXhe/typecho-Comment2Mail

登录后回复评论是报错如下，不知道是bug还是新特性所以问问

```
Typecho\Widget::__construct(): Argument #1 ($request) must be of type Typecho\Widget\Request, Typecho\Request given, called in /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/wp-content/plugins/Comment2Mail/Plugin.php on line 136
TypeError: Typecho\Widget::__construct(): Argument #1 ($request) must be of type Typecho\Widget\Request, Typecho\Request given, called in /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/wp-content/plugins/Comment2Mail/Plugin.php on line 136 and defined in /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/var/Typecho/Widget.php:91
Stack trace:
#0 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/wp-content/plugins/Comment2Mail/Plugin.php(136): Typecho\Widget->__construct()
#1 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/wp-content/plugins/Comment2Mail/Plugin.php(215): Comment2Mail_Plugin::getParent()
#2 [internal function]: Comment2Mail_Plugin::finishComment()
#3 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/var/Typecho/Plugin.php(446): call_user_func_array()
#4 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/wp-content/themes/sinner/functions.php(431): Typecho\Plugin->__call()
#5 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/wp-content/themes/sinner/functions.php(253): ajaxComment()
#6 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/var/Widget/Archive.php(735): themeInit()
#7 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/var/Typecho/Widget.php(155): Widget\Archive->execute()
#8 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/var/Typecho/Router.php(96): Typecho\Widget::widget()
#9 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/index.php(23): Typecho\Router::dispatch()
#10 {main}
```

**Comment by jrotty** [comment]
我用的是旧版插件，报错行数和最新的可能对应不上，下面是报错位置的说明
```
    public static function getParent($comment)
    {
        $recipients = [];
        $db = Typecho_Db::get();
        $widget = new Widget_Base_Comments(new Typecho_Request(), new Typecho_Response());//就是这行引起的报错
        // 查询
        $select = $widget->select()->where('coid' . ' = ?', $comment->parent)->limit(1);
        $parent = $db->fetchRow($select, [$widget, 'push']); // 获取上级评论对象
        if ($parent && $parent['mail']) {
            $recipients = [
                'name' => $parent['author'],
                'mail' => $parent['mail'],
            ];
        }
        return $recipients;
    }
```

**Comment by joyqi** [comment]
直接用`Widget_Base_Comments::alloc()`就行了，不用自己`new`
