### ISSUE TITLE
使用addRoute的相关插件报错

### ISSUE THREAD

**Issue by jrotty** [typecho/typecho#1193]
`Helper::addRoute("sq","/sq","sq_Action",'action');`报错如下
```
Typecho\Widget::widget(): Return value must be of type Typecho\Widget, sq_Action returned
TypeError: Typecho\Widget::widget(): Return value must be of type Typecho\Widget, sq_Action returned in /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/var/Typecho/Widget.php:174
Stack trace:
#0 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/var/Typecho/Router.php(96): Typecho\Widget::widget()
#1 /usr/local/lighthouse/softwares/btpanel/wwwroot/zezeshe.com/index.php(23): Typecho\Router::dispatch()
#2 {main}
```

**Comment by joyqi** [comment]
报错已经告诉你了 `Return value must be of type Typecho\Widget, sq_Action returned`，`sq_Action`必须是`Widget`

**Comment by jrotty** [comment]
懂了 thanks
