### ISSUE TITLE
最新提交 01d9d0c 的几个问题

### ISSUE THREAD

**Issue by moeshin** [typecho/typecho#1212]
### 1. 如果有密码保护文章未登录状态下会报错

```text
Property Widget\User:$uid is not exists
Typecho\Widget\Exception: Property Widget\User:$uid is not exists in D:\Projects\Web\typecho\var\Typecho\Widget.php:401
Stack trace:
#0 D:\Projects\Web\typecho\var\Widget\Base\Contents.php(590): Typecho\Widget->__get()
#1 D:\Projects\Web\typecho\var\Widget\Base\Contents.php(478): Widget\Base\Contents->filter()
#2 [internal function]: Widget\Base\Contents->push()
#3 D:\Projects\Web\typecho\var\Typecho\Db.php(427): array_map()
#4 D:\Projects\Web\typecho\var\Widget\Archive.php(1539): Typecho\Db->fetchAll()
#5 D:\Projects\Web\typecho\var\Widget\Archive.php(763): Widget\Archive->query()
#6 D:\Projects\Web\typecho\var\Typecho\Widget.php(156): Widget\Archive->execute()
#7 D:\Projects\Web\typecho\var\Typecho\Router.php(96): Typecho\Widget::widget()
#8 D:\Projects\Web\typecho\index.php(23): Typecho\Router::dispatch()
#9 {main}
```

### 2. 撰写新文章

```text
Property Widget\Contents\Post\Edit:$title is not exists
Typecho\Widget\Exception: Property Widget\Contents\Post\Edit:$title is not exists in D:\Projects\Web\typecho\var\Typecho\Widget.php:401
Stack trace:
#0 D:\Projects\Web\typecho\var\Widget\Base\Contents.php(658): Typecho\Widget->__get()
#1 D:\Projects\Web\typecho\admin\write-post.php(27): Widget\Base\Contents->title()
```

### 3.创建新页面

```text
Property Widget\Contents\Page\Edit:$title is not exists
Typecho\Widget\Exception: Property Widget\Contents\Page\Edit:$title is not exists in D:\Projects\Web\typecho\var\Typecho\Widget.php:401
Stack trace:
#0 D:\Projects\Web\typecho\var\Widget\Base\Contents.php(658): Typecho\Widget->__get()
#1 D:\Projects\Web\typecho\admin\write-page.php(27): Widget\Base\Contents->title()
```

### 环境

- 操作系统版本：Microsoft Windows [版本 10.0.22478.1000]
- Apache/NGINX 版本：nginx/1.21.3
- 数据库版本：Ver 8.0.26 for Win64 on x86_64 (MySQL Community Server - GPL)
- PHP 版本：PHP 8.0.11 (cli) (built: Sep 21 2021 18:26:06) ( ZTS Visual C++ 2019 x64 )
- Typecho 版本：01d9d0c
- 浏览器版本：Chrome 版本 95.0.4638.54（正式版本） （64 位）

**Comment by dss-saber** [comment]
11
