### ISSUE TITLE
频繁评论时错误页面有问题

### ISSUE THREAD

**Issue by imycard** [typecho/typecho#1234]
### 1. 该问题的重现步骤是什么？
用当前最新同步github代码，使用默认主题，频繁评论激发保护时。
### 2. 你期待的结果是什么？实际看到的又是什么？
期待正常弹出保护提示。实际看到的时错误代码。
对不起, 您的发言过于频繁, 请稍侯再次发布.
Typecho\Widget\Exception: 对不起, 您的发言过于频繁, 请稍侯再次发布. in C:\inetpub\wwwroot\typecho\var\Widget\Feedback.php:128
Stack trace:
#0 C:\inetpub\wwwroot\typecho\var\Typecho\Router.php(99): Widget\Feedback->action()
#1 C:\inetpub\wwwroot\typecho\index.php(23): Typecho\Router::dispatch()
#2 {main}
### 3. 问题出现的环境

操作系统版本：windows11
IIS 版本：10
数据库版本：MariaDB 10.5
PHP 版本：7.4
Typecho 版本：2021/11/8 同步版本
浏览器版本：EDGE V95
<img width="625" alt="截图" src="https://user-images.githubusercontent.com/3360809/141599062-1c826c2d-eef5-4f97-97b0-9005f036b01f.png">

[//]: # (如有图片请附上截图)

**Comment by imycard** [comment]
开着debug的缘故，关了就好了
