### ISSUE TITLE
🛑 升级到1.2.0后出现传递给Typecho\Router::get()的参数必须是字符串类型报错

### ISSUE THREAD

**Issue by xdingya** [typecho/typecho#1527]
### 1. 该问题的重现步骤是什么？
在自己编写的 Api 接口软件中，在原来的版本中调用 Typecho 的类方法正常输出，但是升级到 1.2.0 版本后无法访问，可能是控制器适配这边的问题，但我不确定。
### 报错内容：

```
Argument 1 passed to Typecho\Router::get() must be of the type string, null given, called in /Site/var/Widget/Abstract/Contents.php on line 665

TypeError: Argument 1 passed to Typecho\Router::get() must be of the type string, null given, called in /Site/var/Widget/Abstract/Contents.php on line 665 and defined in /Site/var/Typecho/Router.php:170
Stack trace:

#0 /Site/var/Widget/Abstract/Contents.php(665): Typecho\Router::get(NULL)

#1 /Site/var/Widget/Abstract/Contents.php(761): Widget_Abstract_Contents->filter(Array)

#2 /Site/Api.php(57): Widget_Abstract_Contents->push(Array)

#3 {main}

```
### 代码片段
![2b09c14005ff5f6d](https://user-images.githubusercontent.com/36700883/212928899-3a1d2274-0843-457e-b5dd-04fa2c132c54.jpg)

2. 你期待的结果是什么？实际看到的又是什么？
解决问题就好了！

### 3. 问题出现的环境

- 操作系统版本：Linux
- Apache/NGINX 版本：Nginx
- 数据库版本：正常版本
- PHP 版本：7.2
- Typecho 版本：1.2.0
- 浏览器版本：非IE

**Comment by xdingya** [comment]
非 Typecho 原因
