### ISSUE TITLE
使用 PHP 内置服务器打开站点报错

### ISSUE THREAD

**Issue by lemoncabin** [typecho/typecho#1706]
## 描述这个 Bug

无法使用 PHP 开启自带调试服务器。

### 复现方式

我在全新下载包根目录运行 `php -S localhost:8000 `，然后打开浏览器  `localhost:8000 `，网页重定向到 `install.php`，响应 500。

### 期望的结果

能正常使用 `php -S` 启动轻量级开发服务器。

### 平台

- 操作系统版本：win11
- PHP 版本：8.3
- Typecho 版本：1.3
- 浏览器版本：chrome 最新版

**Comment by sy-records** [comment]
开发时就是用内置服务器跑的。

在install.php文件`<?php`后加入下面代码，可以打开`debug`看下具体错误信息堆栈

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by lemoncabin** [comment]
我试了下集成环境启动，貌似新发布的 `1.3` 的包有问题，无法运行安装，使用了 https://www.phpenv.cn/ 的 EServer 集成环境。
调试报如下错误：

```
Warning: Undefined array key "routingTable" in C:\Users\LemonCabin\Workspace\typecho\var\Widget\Options.php on line 352
Widget\Options::tryDeserialize(): Argument #1 ($value) must be of type string, null given, called in C:\Users\LemonCabin\Workspace\typecho\var\Widget\Options.php on line 352
TypeError: Widget\Options::tryDeserialize(): Argument #1 ($value) must be of type string, null given, called in C:\Users\LemonCabin\Workspace\typecho\var\Widget\Options.php on line 352 and defined in C:\Users\LemonCabin\Workspace\typecho\var\Widget\Options.php:759
Stack trace:
#0 C:\Users\LemonCabin\Workspace\typecho\var\Widget\Options.php(352): Widget\Options->tryDeserialize(NULL)
#1 C:\Users\LemonCabin\Workspace\typecho\var\Typecho\Widget.php(441): Widget\Options->___routingTable()
#2 C:\Users\LemonCabin\Workspace\typecho\var\Widget\Init.php(102): Typecho\Widget->__get('routingTable')
#3 C:\Users\LemonCabin\Workspace\typecho\var\Typecho\Widget.php(155): Widget\Init->execute()
#4 C:\Users\LemonCabin\Workspace\typecho\var\Typecho\Widget.php(187): Typecho\Widget::widget('Widget\\Init', NULL, NULL, true)
#5 C:\Users\LemonCabin\Workspace\typecho\install.php(1421): Typecho\Widget::alloc()
#6 C:\Users\LemonCabin\Workspace\typecho\install.php(1501): install_dispatch()
#7 {main}
```

**Comment by xiamuguizhi** [comment]
@chatgtp4 

从给出的错误信息来看，问题出在 `Options.php` 的 352 行。`tryDeserialize()` 函数尝试处理一个 `null` 值，但这个函数需要一个字符串作为参数。这可能是因为 "routingTable" 键在某个数组中未定义，导致 Typecho 在处理路由表时出现问题。

以下是一种可能的解决方法：

1. 打开 `Options.php` 文件，找到第 352 行。

2. 在调用 `tryDeserialize()` 函数之前，添加一个检查，确保 `$value` 不是 `null`。例如：

   ```php
   if ($value !== null) {
       $value = $this->tryDeserialize($value);
   }
   ```

3. 保存并重新尝试运行服务器。

以上的解决方法只是一个可能的方案，具体的解决方案可能需要对 Typecho 的代码和你的环境有更深入的理解。

**Comment by sy-records** [comment]
Duplicate of #1663
