### ISSUE TITLE
无法登陆-502 Bad Gateway

### ISSUE THREAD

**Issue by ma3252788** [typecho/typecho#1719]
## 描述这个 Bug

不知道什么时候开始，突然就无法登陆了。。其他一切正常，比如查看文章、评论都没问题，就是登陆有问题。

这是宝塔后台站点响应日志：

```
112.38.217.12 - - [24/Jan/2024:17:26:20 +0800] "POST /index.php/action/login?_=b145487f08ace742f286086ba73ab28a HTTP/2.0" 302 0 "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
112.38.217.12 - - [24/Jan/2024:17:26:20 +0800] "GET /dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php HTTP/2.0" 200 2358 "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
112.38.217.12 - - [24/Jan/2024:17:26:54 +0800] "POST /index.php/action/login?_=b145487f08ace742f286086ba73ab28a HTTP/2.0" 302 0 "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
112.38.217.12 - - [24/Jan/2024:17:26:54 +0800] "GET /dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php HTTP/2.0" 200 2358 "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
112.38.217.12 - - [24/Jan/2024:17:26:59 +0800] "POST /index.php/action/login?_=b145487f08ace742f286086ba73ab28a HTTP/2.0" 302 0 "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
112.38.217.12 - - [24/Jan/2024:17:26:59 +0800] "GET /dbb/welcome.php HTTP/2.0" 302 0 "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
112.38.217.12 - - [24/Jan/2024:17:27:02 +0800] "GET /dbb/ HTTP/2.0" 499 0 "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"
```

这是宝塔后台站点错误日志：
```
2024/01/24 16:59:30 [error] 16584#0: *3213015 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "GET /dbb/ HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn", referrer: "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2F"
2024/01/24 17:02:00 [error] 17360#0: *3213182 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /www/wwwroot/www.lzxmt.cn/var/Json.php on line 32" while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "POST /index.php/action/login?_=d4564253b7014034d1a494f7056822b5 HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-80.sock:", host: "www.lzxmt.cn", referrer: "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2F"
2024/01/24 17:18:45 [error] 19013#0: *11 FastCGI sent in stderr: "PHP message: SQLSTATE[HY000] [2002] No such file or directory" while reading response header from upstream, client: 216.245.221.86, server: www.lzxmt.cn, request: "HEAD / HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn", referrer: "https://www.lzxmt.cn"
2024/01/24 17:21:10 [error] 19014#0: *73 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "GET /dbb/ HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn"
2024/01/24 17:21:40 [error] 19014#0: *73 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "GET /dbb/ HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn", referrer: "https://www.lzxmt.cn/"
2024/01/24 17:25:29 [error] 1592#0: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "GET /dbb/ HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn"
2024/01/24 17:26:02 [error] 1592#0: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function format() on null in /www/wwwroot/www.lzxmt.cn/var/Widget/Abstract/Contents.php:773
Stack trace:
#0 /www/wwwroot/www.lzxmt.cn/usr/themes/initial/header.php(17): Widget_Abstract_Contents->date()
#1 /www/wwwroot/www.lzxmt.cn/var/Widget/Archive.php(1937): require('/www/wwwroot/ww...')
#2 /www/wwwroot/www.lzxmt.cn/usr/themes/initial/404.php(2): Widget_Archive->need()
#3 /www/wwwroot/www.lzxmt.cn/var/Widget/Archive.php(2022): require_once('/www/wwwroot/ww...')
#4 /www/wwwroot/www.lzxmt.cn/var/Widget/ExceptionHandle.php(27): Widget_Archive->render()
#5 /www/wwwroot/www.lzxmt.cn/var/Typecho/Common.php(240): Widget_ExceptionHandle->__construct()
#6 [internal function]: Typecho_Common::exceptionHandle()
#7 {main}
  thrown in /www/wwwroot/www.lzxmt.cn/var/Widget/Abstract/Contents.php on line 773" while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "GET /d/dbb/welcome.php HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn"
2024/01/24 17:28:49 [error] 1592#0: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "POST /index.php/action/login?_=b145487f08ace742f286086ba73ab28a HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn", referrer: "https://www.lzxmt.cn/dbb/login.php?referer=https%3A%2F%2Fwww.lzxmt.cn%2Fdbb%2Fwelcome.php"
2024/01/24 17:29:02 [error] 1592#0: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  strpos(): Empty needle in /www/wwwroot/www.lzxmt.cn/usr/plugins/SmartSpam/Plugin.php on line 369PHP message: PHP Warning:  strpos(): Empty needle in /www/wwwroot/www.lzxmt.cn/usr/plugins/SmartSpam/Plugin.php on line 369PHP message: PHP Warning:  strpos(): Empty needle in /www/wwwroot/www.lzxmt.cn/usr/plugins/SmartSpam/Plugin.php on line 369PHP message: PHP Warning:  strpos(): Empty needle in /www/wwwroot/www.lzxmt.cn/usr/plugins/SmartSpam/Plugin.php on line 369" while reading response header from upstream, client: 112.38.217.12, server: www.lzxmt.cn, request: "POST /adln/diray/11.html/comment HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-74.sock:", host: "www.lzxmt.cn", referrer: "https://www.lzxmt.cn/adln/diray/11.html"
```

### 复现方式

复现的步骤：

打开登陆页面之后，输入密码登录，然后就卡死，过了很久会出现502 Bad Gateway

已经重启过服务器了，同服务器的其他typecho 网站都可以登陆，就这个不行。

### 期望的结果

正常进行登录

### 截图

<img width="1068" alt="image" src="https://github.com/typecho/typecho/assets/22229456/60262f69-10ee-429e-9e59-4b50b6f8a04c">

### 平台

- 操作系统版本：CentOS Linux release 7.9.2009 (Core)
- Apache/Nginx 版本：Nginx 1.20.2
- 数据库版本：MySQL 5.6.50
- PHP 版本：PHP7.4
- Typecho 版本：版本 1.1 
- 浏览器版本：版本 120.0.2210.144 (正式版本) (arm64)

**Comment by sy-records** [comment]
你的错误信息里有与主题和插件相关的错误。

登录后是302了，可能需要你自己检查一下nginx配置等

**Comment by ma3252788** [comment]
> 你的错误信息里有与主题和插件相关的错误。
> 
> 登录后是302了，可能需要你自己检查一下nginx配置等

谢谢，检查后发现是插件的问题。
