### ISSUE TITLE
编辑文章和页面时报错 Non-static method Plate::short_code() cannot be called statically

### ISSUE THREAD

**Issue by Iuleoo** [typecho/typecho#1724]
## 描述这个 Bug

在编辑/新建 文章和页面时报错 `Non-static method Plate::short_code() cannot be called statically`

### 截图

![image](https://github.com/typecho/typecho/assets/79144535/e2824f6b-d7d4-4c95-8845-dd6f29ebe273)

加了`define('__TYPECHO_DEBUG__', true);` 完整的错误信息如下
```
Error: Non-static method Plate::short_code() cannot be called statically in /www/sites/www.xxx.me/index/usr/themes/pigeon/libs/plate.php(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code(1) : eval()'d code:338
Stack trace:
#0 /www/sites/www.xxx.me/index/var/Widget/Contents/Post/Edit.php(210): themeFields(Object(Typecho\Widget\Helper\Layout))
#1 /www/sites/www.xxx.me/index/admin/custom-fields.php(4): Widget\Contents\Post\Edit->getDefaultFieldItems()
#2 /www/sites/www.xxx.me/index/admin/write-page.php(49): include('/www/sites/www....')
#3 {main}
```

### 平台

- 操作系统版本：容器部署
- openresty 版本：1.21.4.3-0-focal
- 数据库版本：5.7.44
- PHP 版本：8.2.10
- Typecho 版本：1.2.1
- 浏览器版本：Edge 121.0.2277.83

**Comment by sy-records** [comment]
主题问题，建议联系作者处理。
