### ISSUE TITLE
joyqi/typecho:1.2.1-php7.4-apache版本打开页面详情会出现500 Database Query Error

### ISSUE THREAD

**Issue by Dev-Wiki** [typecho/typecho#1769]
## 描述这个 Bug

打开页面详情会出现500 Database Query Error, 打开非详情页面正常, 比如:

- https://blog.devwiki.net/category/Network/
- https://blog.devwiki.net/tag/gradle/

分类和 tag 都可以, 但是文章详情页面不行, 登录后台页面可以打开 点击登录后仍旧如此

### 复现方式

点击任何详情页面都会出现:

点击文档页面出现错误日志:
```
blog-devwiki-typecho-server-1  | [Wed May 08 18:53:07.723233 2024] [core:notice] [pid 14] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:53:31 +0800] "GET /page/15/ HTTP/1.1" 200 12888 "https://blog.devwiki.net/page/16/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:53:32.860391 2024] [php7:warn] [pid 15] [client 172.29.36.1:38288] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/page/15/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:53:32 +0800] "GET /2015/08/05/Java-Simple-Log.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/page/15/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:53:33.071732 2024] [php7:warn] [pid 16] [client 172.29.36.1:38300] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/page/15/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:53:33 +0800] "GET /2015/07/27/Android-Code-Pattern.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/page/15/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:53:33.681694 2024] [php7:warn] [pid 17] [client 172.29.36.1:38304] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/page/15/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:53:33 +0800] "GET /2016/02/01/Android-Custom-ViewHolder-1.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/page/15/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:53:33.856188 2024] [php7:warn] [pid 18] [client 172.29.36.1:38308] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/page/15/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:53:33 +0800] "GET /2016/03/02/Retrofit-Use-Course-1.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/page/15/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:53:36 +0800] "GET / HTTP/1.1" 200 13371 "https://blog.devwiki.net/page/15/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:53:49 +0800] "GET /category/Harmony/ HTTP/1.1" 200 10509 "https://blog.devwiki.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:54:36.115418 2024] [php7:warn] [pid 15] [client 172.29.36.1:38560] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:54:36 +0800] "GET /2024/03/04/Harmony-app-dev-02-typescript.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:54:58 +0800] "GET /category/tools/ HTTP/1.1" 200 13246 "https://blog.devwiki.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:54:58 +0800] "GET /category/DevTools/ HTTP/1.1" 200 10171 "https://blog.devwiki.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:54:59 +0800] "GET /category/OpenLib/ HTTP/1.1" 200 12198 "https://blog.devwiki.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:54:59 +0800] "GET /category/Network/ HTTP/1.1" 200 11059 "https://blog.devwiki.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:54:59 +0800] "GET /category/database/ HTTP/1.1" 200 9322 "https://blog.devwiki.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:55:12.615620 2024] [php7:warn] [pid 18] [client 172.29.36.1:38646] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/category/Network/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:12 +0800] "GET /archives.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:55:12.678935 2024] [php7:warn] [pid 19] [client 172.29.36.1:38648] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/category/Network/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:12 +0800] "GET /tags.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:55:14.745741 2024] [php7:warn] [pid 20] [client 172.29.36.1:38658] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/category/Network/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:14 +0800] "GET /2018/09/08/change-retrofit-base-url-and-rest-version.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:15 +0800] "GET /category/QT/ HTTP/1.1" 200 11344 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:15 +0800] "GET /category/Windows/ HTTP/1.1" 200 12956 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:16 +0800] "GET /category/NET/ HTTP/1.1" 200 11563 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:16 +0800] "GET /category/wpf/ HTTP/1.1" 200 12515 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:16 +0800] "GET /tag/git/ HTTP/1.1" 200 12674 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:17 +0800] "GET /tag/gradle/ HTTP/1.1" 200 12551 "https://blog.devwiki.net/category/Network/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | [Wed May 08 18:55:20.249097 2024] [php7:warn] [pid 15] [client 172.29.36.1:38664] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/tag/gradle/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:55:20 +0800] "GET /2018/01/02/develop-gradle-plugin-use-idea-with-java.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/tag/gradle/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:56:39 +0800] "GET /tag/gradle/ HTTP/1.1" 200 12563 "-" "Mediapartners-Google"
blog-devwiki-typecho-server-1  | [Wed May 08 18:57:19.757092 2024] [php7:warn] [pid 16] [client 172.29.36.1:39072] PHP Warning:  SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php on line 82, referer: https://blog.devwiki.net/tag/gradle/
blog-devwiki-typecho-server-1  | 172.29.36.1 - - [08/May/2024:18:57:19 +0800] "GET /2018/11/05/question-daily-20181105.html HTTP/1.1" 500 1271 "https://blog.devwiki.net/tag/gradle/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0""
```

使用的映射目录有正常的权限:
![image](https://github.com/typecho/typecho/assets/12946956/ddc3d026-3a6a-4a26-b160-b57d68a1f239)

### 期望的结果

能正常访问页面

### 平台

docker compose安装

```yaml
version: '3'

services:    
  typecho-server:
    image: joyqi/typecho:1.2.1-php7.4-apache
    volumes:
      - /share/Docker/blog_typecho/installer:/app 
      - /share/Docker/blog_typecho/:/app/usr
    environment:
      TIMEZONE: Asia/Shanghai
      TYPECHO_INSTALL: 0
      MEMORY_LIMIT: 100m
      MAX_POST_BODY: 51m
      TYPECHO_SITE_URL: https://blog.devwiki.net
    ports:
      - "2061:80"

```

**Comment by sy-records** [comment]
可以打开`debug`查看具体错误信息堆栈，在`config.inc.php`中加入：

```php
define('__TYPECHO_DEBUG__', true);
```

**Comment by Dev-Wiki** [comment]
> ```
> define('__TYPECHO_DEBUG__', true);
> ```
已经打开: 
[blog.devwiki.net/2018/11/05/question-daily-20181105.html](https://blog.devwiki.net/2018/11/05/question-daily-20181105.html)

attempt to write a readonly database
Typecho\Db\Adapter\SQLException: attempt to write a readonly database in /app/var/Typecho/Db/Adapter/SQLite.php:88
Stack trace:
#0 /app/var/Typecho/Db.php(391): Typecho\Db\Adapter\SQLite->query('UPDATE db_optio...', Object(SQLite3), 2, 'UPDATE', 'db_options')
#1 /app/var/Widget/Plugins/Edit.php(178): Typecho\Db->query(Object(Typecho\Db\Query))
#2 /app/var/Utils/Helper.php(414): Widget\Plugins\Edit::configPlugin('plugin:PageView...', Array, false)
#3 /app/usr/plugins/PageViews/Plugin.php(56): Utils\Helper::configPlugin('PageViews', Array)
#4 [internal function]: PageViews_Plugin::statisticalPageViews(Object(Widget\Archive), NULL)
#5 /app/var/Typecho/Plugin.php(446): call_user_func_array(Array, Array)
#6 /app/var/Widget/Archive.php(1412): Typecho\Plugin->__call('Widget_Archive:...', Array)
#7 /app/var/Typecho/Router.php(99): Widget\Archive->render()
#8 /app/index.php(23): Typecho\Router::dispatch()
#9 {main}

**Comment by sy-records** [comment]
你的 SQLite 是个只读的，不能更新和写入，检查一下吧

**Comment by Dev-Wiki** [comment]
> 你的 SQLite 是个只读的，不能更新和写入，检查一下吧

最近一直没有改动什么 之前还能正常访问, 不知道哪里会导致 变成只读

**Comment by Dev-Wiki** [comment]
> 你的 SQLite 是个只读的，不能更新和写入，检查一下吧

![image](https://github.com/typecho/typecho/assets/12946956/f4c7c782-8389-4d67-97b8-2e6e7ff41e37)
