### ISSUE TITLE
RSS 500 error

### ISSUE THREAD

**Issue by renothing** [typecho/typecho#1778]
升级到最新开发版,rss 出错
```
Typed property Typecho\Feed::$subTitle must be string, null used
TypeError: Typed property Typecho\Feed::$subTitle must be string, null used in /var/www/var/Typecho/Feed.php:143
Stack trace:
#0 /var/www/var/Widget/Feed.php(105): Typecho\Feed->setSubTitle()
#1 /var/www/var/Typecho/Widget.php(155): Widget\Feed->execute()
#2 /var/www/var/Typecho/Router.php(85): Typecho\Widget::widget()
#3 /var/www/index.php(23): Typecho\Router::dispatch()
#4 {main}
```
分类和单篇文章的rss正常

### 平台

- 操作系统版本：Ubuntu 22.04
- Apache/Nginx 版本：1.24.0
- 数据库版本：Mysql 5.7
- PHP 版本：PHP 7.4.32
- Typecho 版本：master
- 浏览器版本：chrome

**Comment by sy-records** [comment]
你没配置站点说明？

**Comment by renothing** [comment]
> 你没配置站点描述？

是的。站点描述为空。
把站点描述补充后就正常。
