### ISSUE TITLE
1.3部分钩子失效

### ISSUE THREAD

**Issue by funnycups** [typecho/typecho#1816]
## 描述这个 Bug

在模板[Aria](https://github.com/Siphils/Typecho-Theme-Aria)的functions.php中，使用
```
Typecho_Plugin::factory('Widget_Abstract_Contents')->contentEx = array('Contents', 'parse');
Typecho_Plugin::factory('Widget_Abstract_Contents')->excerptEx = array('Contents', 'parse');
Typecho_Plugin::factory('Widget_Abstract_Comments')->contentEx = array('Comments', 'parse');
```
处理文章内容，但经调试验证，lib/Contents.php内的parse方法没有被运行。
该问题在1.2.1上没有出现

### 复现方式

复现的步骤：

1. 安装Aria主题
2. 打开一个包含代码块的博文
3. 内容显示存在问题

### 期望的结果

parse方法调用parseHljsWrap方法修改代码块`<pre>`标签的class属性

### 截图

这是目前的显示结果
![image](https://github.com/user-attachments/assets/b9e6c13f-a1bf-420b-ad0f-4cee979e3ecc)
这是1.2.1平台下的显示结果
![image](https://github.com/user-attachments/assets/f93d1dbf-8eb7-494a-a4d9-54e835122d26)

### 平台

- 操作系统版本：CentOS7
- Apache/Nginx 版本：Nginx 1.20
- 数据库版本：MySQL5.6
- PHP 版本：8.0
- Typecho 版本：1.3.0
- 浏览器版本：Chrome129.0.6668.101

**Comment by funnycups** [comment]
更新：这个问题应该是因为部分被重复注册的钩子无法正确运行导致的
例如，smiles插件和aisummary插件同时注册了factory('Widget_Abstract_Contents')->contentEx，但两个插件中只有一个的函数会被正确调用

**Comment by joyqi** [comment]
最新的开发版也有这个问题吗？

**Comment by funnycups** [comment]
> 最新的开发版也有这个问题吗？

我更新到了两天前的最后一次提交，并尝试开关了aisummary插件，该问题仍然存在

**Comment by joyqi** [comment]
能否把`options`表里，`name=plugins`条目的`value`值贴出来看看

**Comment by funnycups** [comment]
> 能否把`options`表里，`name=plugins`条目的`value`值贴出来看看
```json
{"activated":{"Sticky":{"handles":{"Widget_Archive:indexHandle":[["Sticky_Plugin","sticky"]]}},"Smilies":{"handles":{"Widget_Abstract_Comments:contentEx":[["Smilies_Plugin","showsmilies"]],"Widget_Abstract_Contents:contentEx":[["Smilies_Plugin","showsmilies"]],"Widget_Abstract_Contents:excerptEx":[["Smilies_Plugin","showsmilies"]],"Widget_Archive:footer":[["Smilies_Plugin","insertjs"]],"admin\/write-post.php:bottom":[["Smilies_Plugin","smbutton"]],"admin\/write-page.php:bottom":[["Smilies_Plugin","smbutton"]],"Widget_Comments_Archive:callSmilies":[["Smilies_Plugin","output"]]}},"waterMark":{"handles":{"Widget_Upload:upload":[["waterMark_Plugin","render"]]}},"Notice":{"handles":{"Widget_Feedback:finishComment":["TypechoPlugin\\Notice\\Plugin::requestService"],"Widget_Comments_Edit:finishComment":["TypechoPlugin\\Notice\\Plugin::requestService"],"Widget_Comments_Edit:mark":["TypechoPlugin\\Notice\\Plugin::approvedMail"],"Widget_Service:sendSC":["TypechoPlugin\\Notice\\Plugin::sendSC"],"Widget_Service:sendQmsg":["TypechoPlugin\\Notice\\Plugin::sendQmsg"],"Widget_Service:sendMail":["TypechoPlugin\\Notice\\Plugin::sendMail"],"Widget_Service:sendApprovedMail":["TypechoPlugin\\Notice\\Plugin::sendApprovedMail"]}},"TeStore":{"handles":{"admin\/menu.php:navBar":[["TeStore_Plugin","render"]]}},"TpCache":{"handles":{"index.php:begin":[["TpCache_Plugin","C"]],"index.php:end":[["TpCache_Plugin","S"]],"Widget_Contents_Post_Edit:finishPublish":[["TpCache_Plugin","post_update"]],"Widget_Contents_Page_Edit:finishPublish":[["TpCache_Plugin","post_update"]],"Widget_Contents_Post_Edit:delete":[["TpCache_Plugin","post_del_update"]],"Widget_Contents_Page_Edit:delete":[["TpCache_Plugin","post_del_update"]],"Widget_Feedback:finishComment":[["TpCache_Plugin","comment_update"]],"Widget_Comments_Edit:finishDelete":[["TpCache_Plugin","comment_update2"]],"Widget_Comments_Edit:finishEdit":[["TpCache_Plugin","comment_update2"]],"Widget_Comments_Edit:finishComment":[["TpCache_Plugin","comment_update2"]],"Widget_Abstract_Contents:contentEx":[["TpCache_Plugin","cache_contentEx"]],"admin\/write-post.php:bottom":[["TpCache_Plugin","forTpCacheToolbar"]],"admin\/write-page.php:bottom":[["TpCache_Plugin","forTpCacheToolbar"]],"TpCache.Widget_Cache:getCache":[["TpCache_Plugin","TpCache_getCache"]],"TpCache.Widget_Cache:setCache":[["TpCache_Plugin","TpCache_setCache"]]}},"RobotsPlusPlus":{"handles":{"Widget_Archive:header":[["RobotsPlusPlus_Util","isBot"]]}},"Beblank":{"handles":{"Widget_Archive:footer":[["Beblank_Plugin","footer"]]}},"AAThemeDemo":{"handles":{"index.php:begin":[["TypechoPlugin\\AAThemeDemo\\Plugin","route"]],"Widget_Archive:handleInit":[["TypechoPlugin\\AAThemeDemo\\Plugin","setTheme"]]}},"Sitemap":[],"SmartSpam":{"handles":{"Widget_Feedback:comment":[["SmartSpam_Plugin","filter"]]}},"Links":{"handles":{"Widget_Abstract_Contents:contentEx":[["Links_Plugin","parse"]],"Widget_Abstract_Contents:excerptEx":[["Links_Plugin","parse"]],"Widget_Abstract_Comments:contentEx":[["Links_Plugin","parse"]],"Widget_Archive:callLinks":[["Links_Plugin","output_str"]]}},"GAuthenticator":{"handles":{"admin\/common.php:begin":[["GAuthenticator_Plugin","Authenticator_verification"]]}},"AIBaTgrMX":{"handles":{"Widget_Abstract_Contents:excerptEx":[["AIBaTgrMX_Plugin","customExcerpt"]],"Widget_Contents_Post_Edit:write":[["AIBaTgrMX_Plugin","beforePublish"]],"Widget_Archive:header":[["AIBaTgrMX_Plugin","optimizeSEO"]],"Widget_Abstract_Contents:contentEx":[["AIBaTgrMX_Plugin","customContent"]]}}},"handles":{"Widget_Archive:indexHandle":[["Sticky_Plugin","sticky"]],"Widget_Abstract_Comments:contentEx":{"0":["Smilies_Plugin","showsmilies"],"0.001":["Links_Plugin","parse"]},"Widget_Abstract_Contents:contentEx":{"0":["Smilies_Plugin","showsmilies"],"0.001":["TpCache_Plugin","cache_contentEx"],"0.002":["Links_Plugin","parse"],"0.003":["AIBaTgrMX_Plugin","customContent"]},"Widget_Abstract_Contents:excerptEx":{"0":["Smilies_Plugin","showsmilies"],"0.001":["Links_Plugin","parse"],"0.002":["AIBaTgrMX_Plugin","customExcerpt"]},"Widget_Archive:footer":{"0":["Smilies_Plugin","insertjs"],"0.002":["Beblank_Plugin","footer"]},"admin\/write-post.php:bottom":{"0":["Smilies_Plugin","smbutton"],"90":["TpCache_Plugin","forTpCacheToolbar"]},"admin\/write-page.php:bottom":{"0":["Smilies_Plugin","smbutton"],"90":["TpCache_Plugin","forTpCacheToolbar"]},"Widget_Comments_Archive:callSmilies":[["Smilies_Plugin","output"]],"Widget_Upload:upload":[["waterMark_Plugin","render"]],"Widget_Feedback:finishComment":{"0":"TypechoPlugin\\Notice\\Plugin::requestService","0.001":["TpCache_Plugin","comment_update"]},"Widget_Comments_Edit:finishComment":{"0":"TypechoPlugin\\Notice\\Plugin::requestService","0.001":["TpCache_Plugin","comment_update2"]},"Widget_Comments_Edit:mark":["TypechoPlugin\\Notice\\Plugin::approvedMail"],"Widget_Service:sendSC":["TypechoPlugin\\Notice\\Plugin::sendSC"],"Widget_Service:sendQmsg":["TypechoPlugin\\Notice\\Plugin::sendQmsg"],"Widget_Service:sendMail":["TypechoPlugin\\Notice\\Plugin::sendMail"],"Widget_Service:sendApprovedMail":["TypechoPlugin\\Notice\\Plugin::sendApprovedMail"],"admin\/menu.php:navBar":[["TeStore_Plugin","render"]],"index.php:begin":{"0":["TpCache_Plugin","C"],"0.001":["TypechoPlugin\\AAThemeDemo\\Plugin","route"]},"index.php:end":[["TpCache_Plugin","S"]],"Widget_Contents_Post_Edit:finishPublish":[["TpCache_Plugin","post_update"]],"Widget_Contents_Page_Edit:finishPublish":[["TpCache_Plugin","post_update"]],"Widget_Contents_Post_Edit:delete":[["TpCache_Plugin","post_del_update"]],"Widget_Contents_Page_Edit:delete":[["TpCache_Plugin","post_del_update"]],"Widget_Comments_Edit:finishDelete":[["TpCache_Plugin","comment_update2"]],"Widget_Comments_Edit:finishEdit":[["TpCache_Plugin","comment_update2"]],"TpCache.Widget_Cache:getCache":[["TpCache_Plugin","TpCache_getCache"]],"TpCache.Widget_Cache:setCache":[["TpCache_Plugin","TpCache_setCache"]],"Widget_Archive:header":{"0":["RobotsPlusPlus_Util","isBot"],"0.001":["AIBaTgrMX_Plugin","optimizeSEO"]},"Widget_Archive:handleInit":[["TypechoPlugin\\AAThemeDemo\\Plugin","setTheme"]],"Widget_Feedback:comment":[["SmartSpam_Plugin","filter"]],"Widget_Archive:callLinks":[["Links_Plugin","output_str"]],"admin\/common.php:begin":[["GAuthenticator_Plugin","Authenticator_verification"]],"Widget_Contents_Post_Edit:write":[["AIBaTgrMX_Plugin","beforePublish"]]}}
```
已经确认存在问题的地方是factory('Widget_Abstract_Contents')->contentEx，冲突的插件是Smilies和AIBaTgrMX，可以验证一旦启用AIBaTgrMX，Smilies在正文中将不会正常工作，关闭AIBaTgrMX后恢复

**Comment by joyqi** [comment]
我调整了下 [fix/1816](https://github.com/typecho/typecho/tree/fix/1816) ，切换到这个分支看看是否可用

**Comment by joyqi** [comment]
在 config.inc.php 里加上 `define('__TYPECHO_DEBUG__', true);`，看看具体错误是什么

**Comment by funnycups** [comment]
> 在 config.inc.php 里加上 `define('__TYPECHO_DEBUG__', true);`，看看具体错误是什么

后台的错误为：
```
Too few arguments to function Smilies_Plugin::showsmilies(), 2 passed and exactly 3 expected
ArgumentCountError: Too few arguments to function Smilies_Plugin::showsmilies(), 2 passed and exactly 3 expected in /home/blog/wwwroot/usr/plugins/Smilies/Plugin.php:450
Stack trace:
#0 [internal function]: Smilies_Plugin::showsmilies()
#1 /home/blog/wwwroot/var/Typecho/Plugin.php(467): call_user_func_array()
#2 /home/blog/wwwroot/var/Widget/Base/Comments.php(492): Typecho\Plugin->filter()
#3 /home/blog/wwwroot/var/Typecho/Widget.php(462): Widget\Base\Comments->___content()
#4 /home/blog/wwwroot/var/Widget/Base/Comments.php(315): Typecho\Widget->__get()
#5 /home/blog/wwwroot/admin/index.php(83): Widget\Base\Comments->excerpt()
#6 {main}
```
该错误出现在“最近得到的回复”

前台错误为：
```
ArgumentCountError: Too few arguments to function Smilies_Plugin::showsmilies(), 2 passed and exactly 3 expected in /home/blog/wwwroot/usr/plugins/Smilies/Plugin.php:450
Stack trace:
#0 [internal function]: Smilies_Plugin::showsmilies()
#1 /home/blog/wwwroot/var/Typecho/Plugin.php(467): call_user_func_array()
#2 /home/blog/wwwroot/var/Widget/Base/Contents.php(851): Typecho\Plugin->filter()
#3 /home/blog/wwwroot/var/Typecho/Widget.php(462): Widget\Base\Contents->___content()
#4 /home/blog/wwwroot/var/Widget/Base/Contents.php(775): Typecho\Widget->__get()
#5 /home/blog/wwwroot/var/Typecho/Widget.php(462): Widget\Base\Contents->___excerpt()
#6 /home/blog/wwwroot/var/Widget/Base/Contents.php(396): Typecho\Widget->__get()
#7 /home/blog/wwwroot/usr/themes/Aria/index.php(47): Widget\Base\Contents->excerpt()
#8 /home/blog/wwwroot/var/Widget/Archive.php(1345): require_once('...')
#9 /home/blog/wwwroot/var/Typecho/Router.php(88): Widget\Archive->render()
#10 /home/blog/wwwroot/index.php(23): Typecho\Router::dispatch()
#11 {main}
```
该错误在加载文章摘要时出现

**Comment by joyqi** [comment]
更新一下再试试

**Comment by funnycups** [comment]
> 更新一下再试试

更新后，程序不再报错，但注册了factory('Widget_Abstract_Contents')->contentEx的相关函数均没有被执行

**Comment by joyqi** [comment]
Sorry，有一处笔误，再试一下

**Comment by funnycups** [comment]
已经确认可以正常运行了，感谢！
