### ISSUE TITLE
只有在 https 环境下编辑或者发表文章数据库错误

### ISSUE THREAD

**Issue by virusdefender** [typecho/typecho#392]
我在之前的独立主机上 https和 http 都没有问题，但是迁移到一家虚拟主机后每次编辑文章和发表文章的时候都会出错，而且是在 https 环境下这样，http 下没有问题。

```
exception 'Typecho_Db_Query_Exception' in /data/htdocs/virusblog-app.smartgslb.com/var/Typecho/Db/Adapter/Mysql.php:88
Stack trace:
#0 /data/htdocs/virusblog-app.smartgslb.com/var/Typecho/Db.php(353): Typecho_Db_Adapter_Mysql->query(Object(Typecho_Db_Query), Resource id #20, 1, 'SELECT')
#1 /data/htdocs/virusblog-app.smartgslb.com/var/Typecho/Db.php(430): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /data/htdocs/virusblog-app.smartgslb.com/var/Widget/Abstract/Contents.php(245): Typecho_Db->fetchObject(Object(Typecho_Db_Query))
#3 /data/htdocs/virusblog-app.smartgslb.com/var/Widget/Contents/Post/Edit.php(191): Widget_Abstract_Contents->getPageOffset('created', '1440577920', 'post', NULL, '1')
#4 /data/htdocs/virusblog-app.smartgslb.com/var/Widget/Contents/Post/Edit.php(751): Widget_Contents_Post_Edit->getPageOffsetQuery('1440577920')
#5 /data/htdocs/virusblog-app.smartgslb.com/var/Widget/Contents/Post/Edit.php(909): Widget_Contents_Post_Edit->writePost()
#6 /data/htdocs/virusblog-app.smartgslb.com/var/Widget/Do.php(81): Widget_Contents_Post_Edit->action()
#7 /data/htdocs/virusblog-app.smartgslb.com/var/Typecho/Widget.php(222): Widget_Do->execute()
#8 /data/htdocs/virusblog-app.smartgslb.com/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#9 /data/htdocs/virusblog-app.smartgslb.com/index.php(23): Typecho_Router::dispatch()
#10 {main}
```

我在`Typecho/Db.php(353)`前面添加`echo '<div>##################'. (string) $query . '########</div>';`

所以在错误信息上面还有这样的 sql 语句

```
##################SELECT * FROM typecho_options WHERE (`user` = 0 )########
##################SELECT * FROM typecho_users WHERE (`uid` = '1' ) LIMIT 1########
##################SELECT * FROM typecho_options WHERE (`user` = '1' )########
##################UPDATE typecho_users SET `activated` = '1440578826' WHERE (`uid` = '1' )########
```

**Comment by kokororin** [comment]
这是hostker吧，我没有任何问题。

**Comment by kokororin** [comment]
app是不支持写入的，你可以试试老板虚拟主机
