### ISSUE TITLE
PDO SQLite 未初始化

### ISSUE THREAD

**Issue by imoneoi** [typecho/typecho#601]
### 1. 该问题的重现步骤是什么？
使用PDO SQLite适配器 第一个查询带where会报错

### 2. 问题描述
PDO SQLite适配器对象未初始化，导致quote出错

```
Call to a member function quote() on null

Error: Call to a member function quote() on null in C:\Apache24\htdocs\typecho\var\Typecho\Db\Adapter\Pdo.php:141
Stack trace:
#0 C:\Apache24\htdocs\typecho\var\Typecho\Db\Query.php(197): Typecho_Db_Adapter_Pdo->quoteValue('publish')
#1 C:\Apache24\htdocs\typecho\var\Typecho\Db\Query.php(273): Typecho_Db_Query->quoteValues(Array)
#2 C:\Apache24\htdocs\typecho\var\Widget\Archive.php(1357): Typecho_Db_Query->where('table.contents....', 'publish')
#3 C:\Apache24\htdocs\typecho\var\Typecho\Widget.php(221): Widget_Archive->execute()
#4 C:\Apache24\htdocs\typecho\var\Typecho\Router.php(166): Typecho_Widget::widget('Widget_Archive', NULL, NULL)
#5 C:\Apache24\htdocs\typecho\index.php(23): Typecho_Router::dispatch()
#6 {main}

```

### 3.修复方式
在config.inc.php `Typecho_Db::set($db);` 前面加一行 `$db->selectDb(Typecho_Db::READ);`

**Comment by joyqi** [comment]
把你的配置文件完整地贴出来

**Comment by imoneoi** [comment]
```php
<?php
/**
 * Typecho Blog Platform
 *
 * @copyright  Copyright (c) 2008 Typecho team (http://www.typecho.org)
 * @license    GNU General Public License 2.0
 * @version    $Id$
 */

/** 定义根目录 */
define('__TYPECHO_ROOT_DIR__', dirname(__FILE__));

/** 定义插件目录(相对路径) */
define('__TYPECHO_PLUGIN_DIR__', '/usr/plugins');

/** 定义模板目录(相对路径) */
define('__TYPECHO_THEME_DIR__', '/usr/themes');

/** 后台路径(相对路径) */
define('__TYPECHO_ADMIN_DIR__', '/admin/');

/** 设置包含路径 */
@set_include_path(get_include_path() . PATH_SEPARATOR .
__TYPECHO_ROOT_DIR__ . '/var' . PATH_SEPARATOR .
__TYPECHO_ROOT_DIR__ . __TYPECHO_PLUGIN_DIR__);

/** 载入API支持 */
require_once 'Typecho/Common.php';

/** 载入Response支持 */
require_once 'Typecho/Response.php';

/** 载入配置支持 */
require_once 'Typecho/Config.php';

/** 载入异常支持 */
require_once 'Typecho/Exception.php';

/** 载入插件支持 */
require_once 'Typecho/Plugin.php';

/** 载入国际化支持 */
require_once 'Typecho/I18n.php';

/** 载入数据库支持 */
require_once 'Typecho/Db.php';

/** 载入路由器支持 */
require_once 'Typecho/Router.php';

/** 程序初始化 */
Typecho_Common::init();

/** 定义数据库参数 */
$db = new Typecho_Db('Pdo_SQLite', 't_');
$db->addServer(array (
  'file' => 'C:/Apache24/htdocs/typecho/usr/*********.db',
), Typecho_Db::READ | Typecho_Db::WRITE);

/** 这一行是我加入的，可以解决问题 **/
$db->selectDb(Typecho_Db::READ);
/******************************************/

Typecho_Db::set($db);
```

**Comment by joyqi** [comment]
你用的是哪个版本

**Comment by imoneoi** [comment]
刚刚从这里下载的。其他环境测试发现有问题吗？

**Comment by joyqi** [comment]
没有，我在本地一直用SQLite开发，没啥问题

**Comment by imoneoi** [comment]
有用PDO吗

**Comment by joyqi** [comment]
当然，你用这个版本试试
http://typecho.org/build.tar.gz

**Comment by imoneoi** [comment]
没事了，可能我这边代码出了问题？十分感谢

**Comment by imoneoi** [comment]
找到问题了，PDO未初始化导致如果第一个查询带where会报错
我使用了数据库缓存，导致第一个查询带where
正常情况下首先加载options，不带where

触发方式：在config.inc.php最后加入`$db->sql()->where('name = ?', 'test');`
