### ISSUE TITLE
Call to a member function sql() on null

### ISSUE THREAD

**Issue by spiritree** [typecho/typecho#626]
### 1. 该问题的重现步骤是什么？
升级Typecho 1.1(17.10.27)
### 2. 你期待的结果是什么？实际看到的又是什么？
Call to a member function sql() on null
Error: Call to a member function sql() on null in /data/wwwroot/www.spiritree.me/var/Widget/Init.php:31
Stack trace:
#0 /data/wwwroot/www.spiritree.me/var/Typecho/Widget.php(221): Widget_Init->execute()
#1 /data/wwwroot/www.spiritree.me/index.php(17): Typecho_Widget::widget('Widget_Init')
#2 {main}
### 3. 问题出现的环境

- 操作系统版本：Ubuntu16.04
- Apache/NGINX 版本：1.13
- 数据库版本：5.6
- PHP 版本：7.0
- Typecho 版本：1.1

升级前发现根目录出现不明php文件被我删了后升级，不知是否有关联？

**Comment by spiritree** [comment]
var/Widget/Init.php:31
删除下面三行解决
/** 检查安装状态 */
 +        if (!$options->installed) {
 +            $this->update(array('value' => 1), $this->db->sql()->where('name = ?', 'installed'));
 +        }
