### ISSUE TITLE
Database Query Error

### ISSUE THREAD

**Issue by wangdelin** [typecho/typecho#652]
### 1. 该问题的重现步骤是什么？
覆盖升级到17.10.30后，新建文章提示"Database Query Error"
### 2. 你期待的结果是什么？实际看到的又是什么？
不报错
### 3. 问题出现的环境
部署在heroku上面的
- 操作系统版本： Ubuntu 16.04.3 LTS
- Apache/NGINX 版本：
- 数据库版本：
- PHP 版本：5.6.32
- Typecho 版本：1.1 (17.10.30)
- 浏览器版本：

```
ERROR:  syntax error at or near ")"
LINE 1: ...ho_contents WHERE  (typecho_contents."created" >  ) AND (typ...
                                                             ^

exception 'Typecho_Db_Query_Exception' with message 'ERROR:  syntax error at or near ")"
LINE 1: ...ho_contents WHERE  (typecho_contents."created" >  ) AND (typ...
                                                             ^' in /app/var/Typecho/Db/Adapter/Pgsql.php:96
Stack trace:
#0 /app/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pgsql->query('SELECT COUNT(ty...', Resource id #3, 1, 'SELECT')
#1 /app/var/Typecho/Db.php(431): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /app/var/Widget/Abstract/Contents.php(245): Typecho_Db->fetchObject(Object(Typecho_Db_Query))
#3 /app/var/Widget/Contents/Post/Edit.php(193): Widget_Abstract_Contents->getPageOffset('created', NULL, 'post', NULL, '1')
#4 /app/var/Widget/Contents/Post/Edit.php(752): Widget_Contents_Post_Edit->getPageOffsetQuery(NULL)
#5 /app/var/Widget/Contents/Post/Edit.php(910): Widget_Contents_Post_Edit->writePost()
#6 /app/var/Widget/Do.php(82): Widget_Contents_Post_Edit->action()
#7 /app/var/Typecho/Widget.php(221): Widget_Do->execute()
#8 /app/var/Typecho/Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#9 /app/index.php(23): Typecho_Router::dispatch()
#10 {main}
```
[//]: # (如有图片请附上截图)

**Comment by wangdelin** [comment]
数据库版本:  postgresql 9.6.1

**Comment by joyqi** [comment]
之前没这个错误么，完全一样的服务器环境？

**Comment by wangdelin** [comment]
@joyqi 之前没有这个问题，环境也是一样的，会不会跟我的更新方式有关？我是直接从github拉取的最新代码，然后推送到heroku。

**Comment by AurevoirXavier** [comment]
Same problem.
