### ISSUE TITLE
database server error 500

### ISSUE THREAD

**Issue by xieruopeng** [typecho/typecho#743]
Adapter Typecho_Db_Adapter_Pdo_Mysql is not available

Typecho_Db_Exception: Adapter Typecho_Db_Adapter_Pdo_Mysql is not available in /var/www/blog/var/Typecho/Db.php:123
Stack trace:
#0 /var/www/blog/config.inc.php(55): Typecho_Db->__construct('Typecho_Db_Adap...', 'typecho_')
#1 /var/www/blog/index.php(15): include_once('/var/www/blog/c...')
#2 {main}

**Comment by joyqi** [comment]
并没有提供更多的信息

**Comment by xieruopeng** [comment]
Ubutnu16.04，php7.0，mysql数据库可以正常使用。用了几天突然报错500，database server error ，上面是打印出来的错误信息

**Comment by niyanchun** [comment]
我也有这个问题，我在php 7.2.5的时候会报这个错误，换成7.0和7.1就成其他错误了。这说明`Typecho_Db_Adapter_Pdo_Mysql `这个适配器是存在的，但不知道为什么在7.2.5的时候检测不到。我切换会php 5.6之后，又一切正常了。

**Comment by niyanchun** [comment]
我大概定位了一下，应该是`Adapter/Pdo/Mysql.php`里面下下面代码：

```
    public static function isAvailable()
    {
        return parent::isAvailable() && in_array('mysql', PDO::getAvailableDrivers());
    }
```
里面的`in_array('mysql', PDO::getAvailableDrivers()`判断失败了（注释掉这里，只运行前面的parent::isAvailable()，判断是能通过的，只是后面会报找不到driver）。然后我试着把这句话加在主题模板里面看了下输出如下：

```
Array ( [0] => mysql ) 
```
这样看`in_array('mysql', PDO::getAvailableDrivers()`这里不应该是false呀。而且同样的代码，php 5.6是ok的，php 7.x都不行。不懂php，不知道什么问题，求指教。

**Comment by niyanchun** [comment]
我大概知道原因了，我的那个输出是在php 5.6下面输出的，估计我这服务商的php 7.x没有mysql支持，所以`in_array('mysql', PDO::getAvailableDrivers()`是false.

**Comment by skys215** [comment]
php7已经不支持mysql了，请用mysqli

**Comment by niyanchun** [comment]
mysqli和pdo报一样的问题，所以感觉还是php没有装对应的扩展。

**Comment by er567** [comment]
也遇到了同样的问题，请问有人解决了么？

**Comment by wuqi** [comment]
我用的sqlite也出错啊,只是换了个php版本...

**Comment by wdssmq** [comment]
php.ini
找到下边扩展并启用；
extension=pdo_mysql
