### ISSUE TITLE
安装反复出现“Database Query Error”

### ISSUE THREAD

**Issue by Hyijun** [typecho/typecho#943]
### 1. 该问题的重现步骤是什么？
新建一个数据库，跟随安装向导进行配置，出现“安装程序检查到原有数据表已经存在”时，选择“删除原有数据”后，出现Database Query Error错误

### 2. 你期待的结果是什么？实际看到的又是什么？
我希望安装成功，实际安装未成功。
以下是开启调试模式后看到的信息：
```
安装失败!

SQLSTATE[HY000]: General error: 1 no such table: typecho_comments
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1 no such table: typecho_comments in /var/www/html/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /var/www/html/var/Typecho/Db.php(367): Typecho_Db_Adapter_Pdo->query('DROP TABLE type...', Object(PDO), 1, 'SELECT', NULL)
#1 /var/www/html/install.php(404): Typecho_Db->query('DROP TABLE type...')
#2 {main}
```

### 3. 问题出现的环境

- 操作系统版本：raspbian 4.19.88 [( Debian-Pi-Aarch64 )](https://github.com/openfans-community-offical/Debian-Pi-Aarch64)
- Apache/NGINX 版本：Apache/2.4.38
- 数据库版本：SQLite 3.27.2 
- PHP 版本： 7.3.11
- Typecho 版本：最新开发版 https://github.com/typecho/typecho/commit/691b43bc485d77acecd9c10057d2b5e69ee55157
- 浏览器版本：Firefox Nightly 76.0a1 

[//]: # (如有图片请附上截图)

**Comment by kumax1024** [comment]
无需手动创建数据库，只需要给typecho根目录下的usr目录777权限即可。
