### ISSUE TITLE
Database Query Error

### ISSUE THREAD

**Issue by iblueer** [typecho/typecho#998]
### 1. 该问题的重现步骤是什么？

在文章正文页面提交评论（在管理评论页面提交评论就不会）

### 2. 你期待的结果是什么？实际看到的又是什么？

不报错，实际看到了 Database Query Error

完整的报错信息如下：

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'sent' at row 1
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'sent' at row 1 in var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 var/Typecho/Db.php(353): Typecho_Db_Adapter_Pdo->query('INSERT INTO typ...', Object(PDO), 2, 'INSERT')
#1 usr/plugins/CommentToMail/Plugin.php(254): Typecho_Db->query(Object(Typecho_Db_Query))
#2 var/Typecho/Plugin.php(489): CommentToMail_Plugin::parseComment(Object(Widget_Feedback), NULL)
#3 var/Widget/Feedback.php(146): Typecho_Plugin->__call('Widget_Feedback...', Array)
#4 var/Widget/Feedback.php(336): Widget_Feedback->comment()
#5 var/Typecho/Router.php(138): Widget_Feedback->action()
#6 index.php(23): Typecho_Router::dispatch()
#7 {main}

### 3. 问题出现的环境

- 操作系统版本：主机壳家的虚拟主机
- Apache/NGINX 版本： 未知
- 数据库版本：mysql
- PHP 版本：PHP7
- Typecho 版本：版本 1.1 (17.10.30)
- 浏览器版本：chrome 84.0.4147.89（正式版本） （64 位）

[//]: # (如有图片请附上截图)

**Comment by iblueer** [comment]
我关掉了CommentsToMail插件之后就不报错了，估计是插件问题
